version: '2'

services:
    interlock:
        image: ehazlett/interlock:master
        command: -D run
        tty: true
        ports:
            - 8080
        environment:
            INTERLOCK_CONFIG: |
                ListenAddr = ":8080"
                DockerURL = "${SWARM_HOST}"
                TLSCACert = "/certs/ca.pem"
                TLSCert = "/certs/cert.pem"
                TLSKey = "/certs/key.pem"

                [[Extensions]]
                Name = "nginx"
                ConfigPath = "/etc/nginx/nginx.conf"
                PidPath = "/etc/nginx/nginx.pid"
                MaxConn = 1024
                Port = 80
        restart: always
        depends_on:
          - nginx
        volumes:
            - /var/lib/docker/volumes/ucp-node-certs/_data/:/certs
    nginx:
        image: nginx
        entrypoint: nginx
        command: -g "daemon off;" -c /etc/nginx/nginx.conf
        ports:
          - 80:80
        labels:
          - "interlock.ext.name=nginx"
        network_mode: "bridge"
        restart: always

    app:
        image: wasdev/ferret
        ports:
            - 9080
        depends_on:
            - interlock
        labels:
            - "interlock.hostname=test"
            - "interlock.domain=lib"
